version: '3.1'

services:
  ghost:
    image: ghost:2-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - "./data:/var/lib/ghost/content"
    environment:
      NODE_ENV: development
